# docker-compose.override.yml
# This file is automatically used for local development.
# It adds the Caddy service configured for a localhost environment.

version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019" # For Caddy's admin API (optional)
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile
      - caddy_data:/data

volumes:
  caddy_data:
